"""add phone number

Revision ID: c38217bd1fe1
Revises: 9b25a413a955
Create Date: 2021-11-16 19:23:55.785750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c38217bd1fe1"
down_revision = "9b25a413a955"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone_number", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###
